### PR TITLE
Update TeaLeaf for Kokkos v3.0 promotion

### PR DESCRIPTION
**Pull request by alanphumphrey**
This PR addresses issue #6, and removes the Kokkos snapshot bundled with TeaLeaf and allows the use of an externally provided Kokkos installation, including Kokkos v3.0.

It turns out that TeaLeaf was not actually using any deprecated features, only the Kokkos examples in the bundled Kokkos snapshot, which have been removed. TeaLeaf should work out of the box with Kokkos v3.0.

Let me know if you have any problems with this.

### CODE REVIEW

**Comment by tomdeakin** [comment]
I tried to build this against an external build of Kokkos (2.8.00, built for a Volta72 backend with CUDA) but get a lot of build errors.

Looking at the changes to the Makefile, Kokkos with GCC should be the default build now. I think all I have to do is set `KOKKOS_PATH` in my environment and run `make`.
However, this invokes `g++` rather than `nvcc_wrapper`, and I get a lot of errors that start like this:
````
g++ -O3 -march=native -funroll-loops -std=c++11  -fopenmp  -I ./ -I c_kernels/kokkos  -DENABLE_PROFILING -DOPENMP -c c_kernels/kokkos/set_chunk_state.cpp -o obj/kokkos/set_chunk_state.o
In file included from /nfs/software/x86_64/kokkos/2.8.00/volta72/include/Kokkos_Core_fwd.hpp:51,
                 from /nfs/software/x86_64/kokkos/2.8.00/volta72/include/Kokkos_Core.hpp:50,
                 from c_kernels/kokkos/kokkos_shared.hpp:3,
                 from c_kernels/kokkos/set_chunk_state.cpp:1:
/nfs/software/x86_64/kokkos/2.8.00/volta72/include/Kokkos_Macros.hpp:186:40: error: ‘__device__’ does not name a type; did you mean ‘__divtc3’?
   #define KOKKOS_INLINE_FUNCTION       __device__  __host__  inline
                                        ^~~~~~~~~~
/nfs/software/x86_64/kokkos/2.8.00/volta72/include/impl/Kokkos_Utilities.hpp:59:1: note: in expansion of macro ‘KOKKOS_INLINE_FUNCTION’
 KOKKOS_INLINE_FUNCTION
 ^~~~~~~~~~~~~~~~~~~~~~

...
````



If I instead run `make KERNEL_COMPILER=nvcc_wrapper` then the build fails too:
````
nvcc_wrapper -O3 -march=native -funroll-loops -std=c++11  -fopenmp  -I ./ -I c_kernels/kokkos  -DENABLE_PROFILING -DOPENMP -c c_kernels/kokkos/set_chunk_state.cpp -o obj/kokkos/set_chunk_state.o
cc1plus: fatal error: ./: No such file or directory
compilation terminated.
cc1plus: fatal error: c_kernels/kokkos: No such file or directory
compilation terminated.
make: *** [obj/kokkos/set_chunk_state.o] Error 1
````

**Comment by alanphumphrey** [comment]
Hi @tomdeakin,

You are correct in that all that needs to be done now is to set the Kokkos Path and it "should build", with GCC as the default. I tested this on a few machines, but will certainly look at this again. I'm back in the states around August 16 after holiday, but will try to get to this prior.

-Alan

**Comment by alanphumphrey** [comment]
Try these changes and let me know how it goes. I've tested with multiple versions of clang, gnu, and intel compilers, all with and without MPI.

Note that the top-level Makefile is setup to use GNU compilers and MPI wrappers by default, and will need to be modified when changing compilers, MPI options, etc.

**Comment by tomdeakin** [comment]
Apologies for the delay in testing this. I'm still getting more errors than I can copy/paste. The first one is:
```
$ make KERNEL_COMPILER=nvcc_wrapper KOKKOS_PATH=/nfs/software/x86_64/kokkos/2.8.00/volta72/                                                                                             
...
c_kernels/kokkos/kokkos_shared.hpp(19): error: namespace "Kokkos" has no member "OpenMP"                                                                                                            
...         
 ```

**Comment by tom91136** [comment]
Project structure updated with latest Kokkos version support, closing.

**Pull request closed without merging**
